package com.android.mb.schedule.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.mb.schedule.db.Schedule;
import com.android.mb.schedule.db.User;
import com.android.mb.schedule.db.Office;

import com.android.mb.schedule.greendao.ScheduleDao;
import com.android.mb.schedule.greendao.UserDao;
import com.android.mb.schedule.greendao.OfficeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scheduleDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig officeDaoConfig;

    private final ScheduleDao scheduleDao;
    private final UserDao userDao;
    private final OfficeDao officeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scheduleDaoConfig = daoConfigMap.get(ScheduleDao.class).clone();
        scheduleDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        officeDaoConfig = daoConfigMap.get(OfficeDao.class).clone();
        officeDaoConfig.initIdentityScope(type);

        scheduleDao = new ScheduleDao(scheduleDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        officeDao = new OfficeDao(officeDaoConfig, this);

        registerDao(Schedule.class, scheduleDao);
        registerDao(User.class, userDao);
        registerDao(Office.class, officeDao);
    }
    
    public void clear() {
        scheduleDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        officeDaoConfig.clearIdentityScope();
    }

    public ScheduleDao getScheduleDao() {
        return scheduleDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public OfficeDao getOfficeDao() {
        return officeDao;
    }

}
